### ISSUE TITLE
Validation: Add support for address space null pointers.

### ISSUE THREAD

**Issue by elhigu** [KhronosGroupArchives/webcl-validator#12]
One simply needs to reserve space for largest possible pointer dereferences in the address space structures.

Currently we cannot be sure if every address space has enough allocated memory somewhere to actually serve safely all the memory accesses in the program. 

We already collect the information of maximum memory access width for each address space. With that information code should be written, that makes sure that minimum requirements are met or exits the kernel.

**Comment by rylimaki** [comment]
Null pointers for constant and local address spaces have been implemented.

Global null pointer requires the area size check and kernel exit on failure.
