### ISSUE TITLE
Validation: Check unsafe builtin calls.

### ISSUE THREAD

**Issue by elhigu** [KhronosGroupArchives/webcl-validator#13]
Check pointers passed to builtins if possible. Otherwise emit errors.

Currently builtin calls are just left alone. Add logic that checks if there are any pointer arguments in call, then abort transformation.

**Comment by rylimaki** [comment]
We are currently emitting error messages for unsafe builtin calls.

Test cases:
unsafe-builtins.cl
unrecognized-builtins.cl
