### ISSUE TITLE
With multiple devices, all tests fail

### ISSUE THREAD

**Issue by VincentSC** [KhronosGroupArchives/webcl-validator#17]
The function clCreateProgramWithSource in OpenCLValidator::CreateProgram() fails with error -30: the kernel read from std-input is empty for the second device. The "std::string code" should be initialised in OpenCLValidator constructor.

Tested with AMD-drivers, first device Radeon, second CPU.

**Comment by rylimaki** [comment]
Thanks, we'll fix this as soon as possible.
