### ISSUE TITLE
Validation: Fix type relocations.

### ISSUE THREAD

**Issue by rylimaki** [KhronosGroupArchives/webcl-validator#18]
Currently typedefs are relocated but structures aren't. Anonymous structures aren't named correctly after relocation.

**Comment by elhigu** [comment]
This was pretty hard to do after all, there is being too many transformations done in one pass so now we added normalizing pass which first prepares code for instrumentation. This way design can be kept more extendible.

**Comment by elhigu** [comment]
Actually type relocation is already implemented, but type normalisation is still needed.

**Comment by elhigu** [comment]
typedefs and structure type declarations are moved to top of the file and name collisions are catched.
