### ISSUE TITLE
Optional: Upstream Clang patches.

### ISSUE THREAD

**Issue by rylimaki** [KhronosGroupArchives/webcl-validator#36]

**Comment by elhigu** [comment]
I started compiling trunk llvm + clang to finish the patches and add required test case.

**Comment by elhigu** [comment]
I'm still having some problems getting added callback to be called in unit test context.

**Comment by elhigu** [comment]
http://blog.gmane.org/gmane.comp.compilers.clang.scm/81570

**Comment by elhigu** [comment]
Pinged about this week ago + also in #llvm irc channel. http://article.gmane.org/gmane.comp.compilers.clang.scm/82216

It could help if someone from amd, nokia, qualcom, samsung or other non-vincit email could reply to this and ask if the patch is getting reviewed.

**Comment by steveneliuk** [comment]
I shall take a look Mikael, did you ever receive any feedback from those guys?

**Comment by elhigu** [comment]
No, there has not been yet any response from clang people who are usually reviewing incoming patches.

**Comment by elhigu** [comment]
I sent another reminder about it and now it got some response. Patch was mostly fine according to first review. I'll update the patch some time this week.

Link to response: http://thread.gmane.org/gmane.comp.compilers.clang.scm/82216/focus=82990

**Comment by elhigu** [comment]
The patch was committed to trunk.
