### ISSUE TITLE
Preprocessing: Add separate preprocessing stage before validation.

### ISSUE THREAD

**Issue by elhigu** [KhronosGroupArchives/webcl-validator#4]
Otherwise done but we need to debug Clang tooling to fit the two validator stages together.

**Comment by elhigu** [comment]
@rylimaki:  Is this still valid issue?

**Comment by elhigu** [comment]
Probably macro expansion would be good thing to do before our pass, since it would also mean that out macros can't be called from user input code.

**Comment by rylimaki** [comment]
Fixed.
