### ISSUE TITLE
Several regression tests fail on Intel OpenCL on Linux

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#40]
The following regression tests are failing on Intel OpenCL running on 64-bit Linux:
- 3d-images.cl
- relocate-types.cl
- rename-types.cl

The original (uninstrumented) kernels are valid according to opencl-validator.

**Comment by toaarnio** [comment]
The latter two tests are still failing. Here's the output from the test suite in case you can't reproduce the error:

## relocate-types.cl:

/disk/llvm-build/bin/opencl-validator: Can't build OpenCL program.
:1:1: error: unknown type name 'Error'
:1:7: error: expected identifier or '('

## remove-variables.cl:

Stack dump:
0.      Running pass 'Simple Register Coalescing' on function '@remove_variables'
/disk/llvm-build/tools/clang/tools/webcl-validator/test/Output/remove-variables.cl.script: line 2: 13327 Done
         /disk/llvm-build/bin/webcl-validator /disk/llvm/tools/clang/tools/webcl-validator/test/remove-variables.cl 2> /
dev/null
     13328                       | grep -v "Processing|CHECK"
     13329 Segmentation fault      | /disk/llvm-build/bin/opencl-validator

**Comment by elhigu** [comment]
relocate-types.cl should still fail on every platform, there is fix coming. 

remove-variables.cl: also fails with Compiling input for Apple/Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz.

CVMS_ERROR_COMPILER_FAILURE: CVMS compiler has crashed or hung building an element.--

Maybe it is related to intel issue. I'm planning to look into this after code cleanup.

**Comment by elhigu** [comment]
Does some tests still fail?

**Comment by rylimaki** [comment]
Transformed version of remove-variables.cl causes the Intel driver to crash.

**Comment by rylimaki** [comment]
The remaining crash is a bug in Intel driver.
