### ISSUE TITLE
Validator output contains three lines of spurious text

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#41]
Running the validator as follows:

```
webcl-validator extension-disable.cl >extension-disable-instrumented.cl
```

The first three lines of `extension-disable-instrumented.cl` now read:

```
Processing: /disk/llvm/tools/clang/tools/webcl-validator/test/extension-disable.cl.
Processing: /tmp/wclZWUlPo.
Processing: /tmp/wclwsCdP5.
```

As a result, the generated CL code does not compile until the first three lines are removed.

**Comment by rylimaki** [comment]
Fixed in latest repositories. Clang 3.3 should also take care of this by replacing outs() with dbgs() in this context.
