### ISSUE TITLE
Error renaming tmp file when running under Cygwin

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#42]
I was able to build the validator under Cygwin, and it seems to be working except for this one error:

```
error: unable to rename temporary '/tmp/wclzLv2Jg-3d9d21cf'
to output file '/tmp/wclzLv2Jg': 'Permission denied'
```

The error originates from `/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp`, line 455:

```
if (llvm::error_code ec = llvm::sys::fs::rename(it->TempFilename,
```

Interestingly, Clang itself is working fine, even though the error comes from the Clang codebase. Perhaps there is something that the validator is doing wrong, or at least differently, with respect to tmp files?

**Comment by elhigu** [comment]
I was able to reproduce this kind of problem on mingw 4.6.4 and msys. Working on it.

**Comment by elhigu** [comment]
I was able to fix this one, but with msys + mingw I did run to another problem. Could you Tomi please check what Cygwin thinks about the latest code?

**Comment by toaarnio** [comment]
Still getting the same error on cygwin: 

error: unable to rename temporary '/tmp/wclI4FQmN-1a40c9e6' to output file '/tmp/wclI4FQmN': 'Permission denied'

**Comment by toaarnio** [comment]
The validator now works on Cygwin.
