### ISSUE TITLE
Sampler addressing mode CLK_ADDRESS_NONE should be flagged as an error

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#43]

**Comment by toaarnio** [comment]
This is potentially more complicated than it seems. 

First of all, it's not sufficient to just remove the CLK_ADDRESS_NONE enum from our header files and let the parser throw an error if the kernel is using it. Because sampler_t is defined as bitfield, a malicious user can assign an arbitrary integer to it, and the underlying OpenCL C compiler will probably accept that.

Secondly, the underlying compiler may also accept an arbitrary integer in place of a sampler_t when calling read_image(). The validator must safeguard against that.

Finally, the numeric values of CLK_ADDRESS_NONE and the other enums are implementation dependent. In other words, we don't know the set of legal numeric values for sampler_t at validation time.

**Comment by elhigu** [comment]
Maybe we could require that WEBCLK_ADDRESS_\* types are used with specified values and validator validates and instrumentation fixes these to vendor specific CLK_ADDRESS_\* defines.

**Comment by toaarnio** [comment]
So we concluded offline that we don't need to introduce any special WEBCLK enums. Our safeguarded implementation of read_image() will just do a compile-time check that the sampler enum value is legal.
