### ISSUE TITLE
OPTIMIZATION: Remove unnecessary builtin declarations from parsing to reduce transformation overhead from 500ms -> 50ms

### ISSUE THREAD

**Issue by elhigu** [KhronosGroupArchives/webcl-validator#46]
Currently parsing through all builtin declarations takes around 450ms  (13" MacBook pro )of total instrumentation time, which is a lot. 

Reason why we have all builtin declarations in parsing is that we have kernel.h header file, which declares all the OpenCL types and builtin declarations, which were not declared automatically by clang opencl frontend (clang does not declare even vector types by itself). 

In current algorithm these builtin declarations were used to recognize all valid builtin functions (we could give error if user calls undeclared external function). However now that we are looking it more close, this design causes huge unnecessary overhead, because parsing through all builtin declarations and building AST for them is relatively slow and it did accumulate on every compiler pass where we had to re-parse.

There are various ways to reduce required header size and following two are not the only options, but the first ones that came to me in two minutes thinking session.

Option 1: Find out all used builtins and add declarations only for those.
We can add separate pass which does not include kernel header except for OpenCL types and find a list of builtins used in kernel code. Separate pass is required, because this needs to be done before preprocessing stage which reads in all the activated builtins pointed by analyse pass. Analyse pass won't cause big overhead since it only reads the kernel code and stores analysis data, it does not have to parse kernel header nor write anything to disk. Estimated time required for analysis is < 10ms.

Option 2: Remove all builtin declarations from parsing and just expect that all calls to external function are builtins.
We can add more validation logic to check that called builtin is ok in out tool or we can assume that called function is call to builtin and leave decision to backend driver if the call was actually builtin call.

Solution 1 is probably easier to write overall, good things in it is that we do not have to write so extensive validation logic to know if certain call is valid builtin with correct argument list. Solution 2 is nice because it would execute faster and we would not have to keep up valid builtin declarations in header file, but we would just define logic according to OpenCL specs which kind of builtins actually exists and which does not.

**Comment by steveneliuk** [comment]
Thank you for the details, 

Could you detail what parsing entails? One is only interested in the questionable built-ins that have pointers... and there are only a limited number of them. What about adding this to the normalization process instead of adding another visiter pass of the AST?

**Comment by steveneliuk** [comment]
Also, Mikael if you could better define compilation i would appreciate it. Reason being is we are instrumenting the code and not compiling it. For instance, we have the parsing, syntactic, semantic checks, and then we have the analysis and instrumentation / translation. I know you have also added in a normalization stage,

However, for compilation the native driver is still used.

Thanks,

**Comment by elhigu** [comment]
I tried to explain the case with a bit more detail. Using the word "compilation" was wrong indeed. I was meaning to talk about parsing, building AST and rewriting the code.

**Comment by toaarnio** [comment]
In my experience, we can't trust CL compilers to reject non-standard external function calls. They all have their own proprietary functions, sometimes even including C stdlib stuff.

**Comment by elhigu** [comment]
Actually we have already implemented most of the fixes, rest of the optimization opportunities are in separate issues.
