### ISSUE TITLE
Validate image2d_t passed in to read_image() and write_image() 

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#47]
The safeguarded implementations of read_image() and write_image() must ensure that their image2d_t argument is one of the image2d_t's passed in as kernel arguments, non-modified.

Preferably, read_image() should check that the image2d_t is not declared as `write_only`, and similarly write_image() should check that it's not `read_only`. Also note that `read_only` is the default.

**Comment by elhigu** [comment]
This has been implemented by Olli some time ago.
