### ISSUE TITLE
Output kernel arg info as JSON

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#48]
The validator should be able to output complete kernel argument info (including names, qualifiers, datatypes, etc.) into a comment block at the beginning of the validated kernel, formatted as JSON.

In case there there are multiple kernels in one source file, there should be only one JSON block at the beginning of the file, with entries for each kernel.

**Comment by steveneliuk** [comment]
However, if this is library form the JSON data isnt needed... one could just pass the data back.

Either way, it is simple enough to include in the header of the kernel, but effortless if the validator is in library form and an method call provides the info. Could return a std::map / std::vector,

**Comment by toaarnio** [comment]
It's a good idea to have both, but if I had to choose one, I'd go for JSON in code comments. That gives the option to use the validator as a separate process or a command-line utility.

**Comment by steveneliuk** [comment]
One has to parse that then... seems more simplistic if we move towards the library.

**Comment by toaarnio** [comment]
"Parsing" JSON in JavaScript amounts to one line of code. By contrast, using an API like clGetKernelArgInfo, you'll end up constructing and populating an equivalent JSON object in your own code.

The existing command-line validator is highly useful, and we shouldn't replace it with a library. We need to be able to build both a library and a command-line validator from the same source.

**Comment by steveneliuk** [comment]
But your not parsing it in JS... the backend is c++ and a little frontend JS.

**Comment by toaarnio** [comment]
It's your choice as an implementor to parse it in JS or in native code. If you don't want to use JS, there are more than two dozen parsers to choose from at http://www.json.org for C/C++.

I'm not aware of any structured data format that would be more convenient or widely supported than JSON. An API similar to clGetKernelArgInfo can be easily layered on top of that.

**Comment by steveneliuk** [comment]
There is no difficulty in parsing... but why when a lib would simply fill / return the data? Shouldnt one try to stay in sync with WebGL?

**Comment by toaarnio** [comment]
I'm not arguing against having a clGetKernelArgInfo equivalent API in the validator, but given that we already have the JSON output in place (see the latest commit a few days ago), I think this ticket can be closed. Please file a new ticket about the kernel arg info API.

**Comment by rylimaki** [comment]
> The validator should be able to output complete kernel argument info (including names, qualifiers, datatypes, etc.) into a comment block at the beginning of the validated kernel, formatted as JSON.

I'll just remind that we haven't implemented qualifiers yet. The __read_only and __write_only qualifiers of image2d_t arguments aren't exported in any form. Please reopen if qualifier information is needed.

**Comment by toaarnio** [comment]
Yes, qualifiers are needed, reopening. Is there anything else that's missing?

**Comment by rylimaki** [comment]
Summary of qualifiers:
1. cl_mem parameters have a field called "address-space" and its value is "global", "local" or "constant". This was already implemented previously.
2. image2d_t parameters have a field called "access" and its value is "read_only" or "write_only". This was added today.

I don't think there is need to support other qualifiers. For example, global address space arrays could be const qualified in the kernel, but I don't think that this information is needed in the host side.
