### ISSUE TITLE
webcl-validator + webcl-translator

### ISSUE THREAD

**Issue by wolfviking0** [KhronosGroupArchives/webcl-validator#53]
Hi,

I start doing some test adding the validator inside the translator. The translator it's based on emscripten/llvm, I just add some option inside inside emscripten for automatically call kernel file when it builds the sample.
The translator convert the c++/opencl file and add the parameter size inside the kernel automatically.
For the moment, I only test the first basic sample I have. 
hello_world doesn't have kernel file but I can test if the code work only with original kernel
hello_world_2 it's working well, it's convert the cl file with validator and the translator make the call on the extra parameter.
convolution it's doing everything without exception, but the result it's wrong. I will check if something it's wrong in my code.

I do the add ons quickly, and it's not yet documented on my wiki page. Just for keep you updated :)

Tony

**Comment by wolfviking0** [comment]
The support inside the webcl-translator it's almost done.
You can build your OpenCL sample like :

hello_world_sample: 
        $(CXX) hello_world.cpp -s CL_VALIDATOR=1 -s CL_VAL_PARAM='["-DPARAM_MAX_DEPTH""]' \
        --preload-file hello_world.cl \
        -o hello_world.js

The translator automatically before preload file, if the file is kernel file (*.cl) it's calling the validator with parameter on the kernel and add the generated kernel to the js data.

I start to update the translator samples with validator on my website : http://wolfviking0.github.io/webcl-translator/

Tony

**Comment by elhigu** [comment]
I'm not sure if this is very persistent place to have this information. Maybe we could add some short description and link directly to your examples from readme.md?

**Comment by elhigu** [comment]
Added link to README.md
