### ISSUE TITLE
Vector versions of math built-ins not recognized

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#54]
The validator incorrectly outputs

```
error: passing 'float4' to parameter of incompatible type 'double'
```

when validating the following kernel:

```
kernel void vectorMathBuiltinBug() 
{
  float4 foo = sqrt((float4)(1.0f));
}
```

**Comment by toaarnio** [comment]
Has this been fixed? I just did a git pull + recompile, and I'm still getting the error:

```
/tmp/wcl8satrl:3:16: warning: implicitly declaring library function 'sqrt' with type 'double (double)'
  float4 foo = sqrt((float4)(1.0f));
               ^
/tmp/wcl8satrl:3:16: note: please include the header <math.h> or explicitly provide a declaration for 'sqrt'
/tmp/wcl8satrl:3:21: error: passing 'float4' to parameter of incompatible type 'double'
  float4 foo = sqrt((float4)(1.0f));
```

**Comment by elhigu** [comment]
Yep, and there is test case for it. 

I also just got lastest master and ran it manually: 

`webcl-validator test/wclv54-vector-builtin-overloads.cl`

Which did produce instrumented result.

**Comment by toaarnio** [comment]
My mistake, was accidentally using an obsolete executable that happened to be earlier along $PATH. It's working now, closing this ticket.
