### ISSUE TITLE
"const sampler_t" incorrectly treated as non-const by read_imagef()

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#55]
The validator incorrectly outputs

```
error: read_image sampler_t is not a constant argument
```

when validating the following kernel:

```
kernel void samplerDeclarationBug(image2d_t src) 
{
  const sampler_t sampler = 
    CLK_NORMALIZED_COORDS_FALSE |
    CLK_ADDRESS_MIRRORED_REPEAT |
    CLK_FILTER_NEAREST;

  float4 sample = read_imagef(src, sampler, (int2)(0, 0));
}
```

**Comment by elhigu** [comment]
To better describe correct handling of sampler_t: 

Sampler_t arguments used in image builtins must meet one of the following requirements:
1. sampler_t is constant which can be evaluated at compile time.
2. sampler_t is given in kernel argument and is not modified before using it in read/write image call.

This ticket can be closed, when there are test cases added to cover both of the valid cases and some invalid cases and working implementation for verification.

**Comment by steveneliuk** [comment]
Sorry for the duplicate bug, that was a real world example though.

Why is this error still coming up? The sampler is const, by definition.

How do we work around this? Is there some uncertainty, or questionable behaviour?

**Comment by steveneliuk** [comment]
Furthermore, sadly 'read_image{i,f}' both support bitwise `|` with a const sampler_t passed in as an argument or as a function global declaration. This behaviour was seen on OXS 10.8.5 OCL driver version 1.1 CPU (intel i7), and OCL driver version 1.0 GPU (AMD Radeon).

**Comment by elhigu** [comment]
I did try the failing case with latest code. Case didn't fail anymore.

**Comment by steveneliuk** [comment]
Great!!! Thanks for the quick update, we shall test.
