### ISSUE TITLE
Implement coordinate validation for write_image*()

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#66]
The specification for `write_image{f,i,ui}` says:

> The behavior of write_imagef, write_imagei and write_imageui for image objects created with image_channel_data_type values not specified in the description above or with (x, y) coordinate values that are not in the range (0... image width - 1, 0... image height - 1), respectively, is undefined. 

The validator is currently not checking that the (x, y) coordinates are within the valid range. I'm not sure if that was in the project plan, but if not, we need to add it there and possibly cut back on the optimizations to stay within budget. Alternatively, we can disallow `write_image` altogether.

Note that coordinate validation doesn't require any extra kernel arguments, because image dimensions can be queried with the `get_image_dim` built-in function (http://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/get_image_dim.html). 

(The validator is also not checking that `image_channel_data_type` is as expected, but that's not a security issue unless there's a bug in the underlying OpenCL driver, in which case the driver can be blacklisted.)

**Comment by elhigu** [comment]
I think we need to add safe wrapper for write image that will make run-time check to support this.
