### ISSUE TITLE
Add instrumentation for kernel-to-kernel function calls

### ISSUE THREAD

**Issue by toaarnio** [KhronosGroupArchives/webcl-validator#68]
OpenCL C allows kernels to call other kernels, and we've decided to support that also in WebCL. Thus, kernel-to-kernel function calls must be properly instrumented to pass buffer sizes from caller to callee.

**Comment by elhigu** [comment]
Added issue #75 which explains why feature is harder that it seems to be.

**Comment by toaarnio** [comment]
Decided to disallow kernel-to-kernel calls instead, closing this ticket.
