### ISSUE TITLE
radix-sort test case may use too much constant memory on a GPU

### ISSUE THREAD

**Issue by rylimaki** [KhronosGroupArchives/webcl-validator#69]
The radix-sort test case can't run stream_count_kernel, because a too large constant memory buffer is passed to kernel.

The size of buffer passed as "__constant uint *unsorted_elements" is 320 kB, whereas minimum that needs to be supported is 64 kB. My NVidia GTX 770 supports only the minimum, which can be determined by querying CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE.

This causes clEnqueueNDRangeKernel to return CL_INVALID_KERNEL_ARGS. The easy work-around is use __global instead of __constant for unsorted_elements.

**Comment by elhigu** [comment]
Fix sounds good. Thanks for checking it out! Could you ask from Erkki if he could include fix to his llvm 3.4 porting branch.
