### ISSUE TITLE
Fix handling opencl extensions.

### ISSUE THREAD

**Issue by elhigu** [KhronosGroupArchives/webcl-validator#78]
Library API of validator allows passing list of extensions that are allowed for certain platform. However logic is still missing, which e.g. enables `half` types or builtin functions for handling those only if extension was enabled with `#pragma OPENCL EXTENSION`. 

This should handle all extension that are currently supported by webcl. Actually I only saw fp16, fp64 and gl_sharing extensions which are mentioned in webcl specs.

Should we also support e.g. cl_khr_global_int32_base_atomics etc.? What is the complete list we need to support?

**Comment by toaarnio** [comment]
The validator should accommodate a larger set of extensions than is currently exposed by WebCL. There are a number of extensions waiting to be exposed as soon as we have the core spec and implementations in good enough shape. Some of them don't have any impact on the kernel language, though, so they can be ignored (such as cl_khr_gl_sharing). 

I came up with the following list of extensions that a) have an impact on kernel language, and b) will have to be supported in WebCL at some point:

```
cl_khr_fp64
cl_khr_fp16
cl_khr_global_int32_base_atomics
cl_khr_global_int32_extended_atomics
cl_khr_local_int32_base_atomics
cl_khr_local_int32_extended_atomics
cl_khr_int64_base_atomics
cl_khr_int64_extended_atomics
```

**Comment by elhigu** [comment]
For this also safe wrappers for atomic builtins are required.

**Comment by toaarnio** [comment]
Note that correct handling of `cl_khr_fp64` requires disallowing all the `doubleN` datatypes. This can be done with a simple `#define`. (Ideally we would also disallow fp64 literals, but that's probably too much effort for relatively little gain.)

**Comment by elhigu** [comment]
merged to master
