### ISSUE TITLE
build failed with tuple include

### ISSUE THREAD

**Issue by wolfviking0** [KhronosGroupArchives/webcl-validator#88]
Hi,

I just update the last change of the validator and I have some trouble for build it 

./clang/tools/webcl-validator/lib/WebCLTransformer.hpp:36:10: fatal error: 
      'tr1/tuple' file not found
# include <tr1/tuple>

```
     ^
```

**Comment by elhigu** [comment]
Yes, I accidentally broke build in OSX few hours ago. We are fixing this. I'll close the ticket when everything is fine again.

**Comment by elhigu** [comment]
Now compiling on OSX and Windows should work again. Please close issue if it now works for you as well.

**Comment by wolfviking0** [comment]
Thanks @elhigu it's working.
