### ISSUE TITLE
error: unknown type name  '_WclProgramAllocations'

### ISSUE THREAD

**Issue by wolfviking0** [KhronosGroupArchives/webcl-validator#95]
Hi, one of my basic sample is not working recently with the validator. It's just an image copy. The kernel take only two image2d_t. After use the validator, I have a build failure apparently, it doesn't know the type _WclProgramAllocations

```
    Parameter detect GPU device
    CL_BUILD_PROGRAM_FAILURE<program source>:85:26: error: unknown type name         '_WclProgramAllocations'
    void _wcl_write_imagef_1(_WclProgramAllocations* _wcl_allocs, image2d_t arg0, int2         arg1, float4 arg2)
                             ^
    <program source>:89:22: error: argument 'arg0' must have either a write_only or                         read_write access qualifier
            write_imagef(arg0, arg1, arg2);
                         ^
    <program source>:106:22: error: use of undeclared identifier '_wcl_allocs'
     _wcl_write_imagef_1(_wcl_allocs, image2, (int2)(xout,yout), pixel);
                         ^

    Error: Arg 1 : clSetKernelArg(-48)
```

**Comment by elhigu** [comment]
That is strange, looks like a bug in instrumentation maybe even in rewriting. Could you give direct link to opencl kernel code and we'll take a look.

**Comment by wolfviking0** [comment]
You an take a look to the kernel here : 
https://github.com/wolfviking0/webcl-translator/blob/master/webcl/imagecopy/image_copy.cl

**Comment by elhigu** [comment]
Thanks. Looks like in that particular case there is no limits in a program, which requires to be put to bookkeeping, so _wcl_allocs is not created at all. Anyways extra argument is always added to helper function calls and signature, which causes failure.

We'll fix this by always creating _wcl_allocs pointer even if it is set to null. I might be able to get fix done even today.

**Comment by elhigu** [comment]
This should work now, please close if everything is ok.

**Comment by wolfviking0** [comment]
The problem is solve, now the sample give the issue #96, bu we can close this.
