### ISSUE TITLE
error : argument 'arg0' must have either a write_only or read_write access qualifier

### ISSUE THREAD

**Issue by wolfviking0** [KhronosGroupArchives/webcl-validator#96]
I have an other issue on two other kernel : 

[Error] <program source>:123:22: error: argument 'arg0' must have either a write_only or read_write access qualifier
[Error]         write_imagef(arg0, arg1, arg2);

https://github.com/wolfviking0/webcl-book-samples/blob/master/src/Chapter_8/ImageFilter2D/ImageFilter2D.cl

https://github.com/wolfviking0/webcl-book-samples/blob/master/src/Chapter_10/GLinterop/GLinterop.cl

**Comment by ollisal** [comment]
Thanks for spotting.

I'd trace this here: https://github.com/KhronosGroup/webcl-validator/blob/d25a92d97c7301fe9d4afcc6a842aef97d5f26f8/lib/WebCLTransformer.cpp#L401

The type returned by clang::QualType::getAsString() doesn't seem to include image access qualifiers at this point. It's implemented by Qualifiers::print() in clang/lib/AST/TypePrinter.cpp. That code only honors const/volatile/restrict and OpenCL address spaces, not image access qualifiers.

We probably have to inject the image access qualifier ourselves, at least for now. I'd consider this a Clang bug in the medium term, however.

**Comment by elhigu** [comment]
This should be fine. Now we add qualifiers also to generated safe builtin wrappers.
